# This is the workflow which display in the Action tab
name: CICD

#manual click deliver workflow whenever user needs
on:
 workflow_dispatch: 
   inputs:
     environment:
       description: This is the environment value where this workflow runs
       default: 'dev' 
       required: true
       type: choice
       options:
         - dev
         - prod
         - stage

jobs:
# every job needs seperat runner, its called parallelism
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone from github"
        
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: build the code
        run: echo "docker container build"
        
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test the container
        run: echo "test the container"
        
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy the 
        run: echo "deploying the application"
    
