# This is workflow name
name: Hello
# runs on a trigger 
on:
  push:
    branches: [main]

# These are jobs inside the workflows
jobs: 

# This is the name of the job
  greet: 
# This is github runner, each job runs on a runner 
    runs-on: ubuntu-latest
  
    steps:
      - name: say hello to users
        run: echo "Hello Dosto"

      - name: say hello to username
        run: echo "Hello $USER"

# This job is to check the details 
  details:
    runs-on: ubuntu-latest

    steps:
      - name: check the version of docker
      - run: docker --version
   
